#!/usr/bin/env python3
"""Regenerate/check bit-reader vectors using the vendored C minimp3 helper.

Requires Python 3, MoonBit's moonfmt, and a C99 compiler (GCC by default).
Uses no network or third-party Python packages.
Normal MoonBit tests consume the generated file without compiling any C.
"""

from __future__ import annotations

import argparse
import hashlib
import os
from pathlib import Path
import subprocess
import tempfile


ROOT = Path(__file__).resolve().parent.parent
HEADER = ROOT / "third_party/minimp3/minimp3.h"
HEADER_SHA256 = "57e437c5c1f0e8b243885d3929c8973b5e6c778451e0100ab4251d19915cb3ad"
DESTINATION = ROOT / "internal/bitstream/upstream_vectors_test.mbt"


def render(values: list[int]) -> str:
    if len(values) != 4 * 8 * 32:
        raise ValueError(f"Expected 1024 oracle values, got {len(values)}")
    if any(value < 0 or value > 0xFFFFFFFF for value in values):
        raise ValueError("Oracle emitted a value outside UInt32")
    lines = [
        "// Generated by tools/generate_bitstream_vectors.py; do not edit.",
        "// Oracle: actual minimp3.h bs_init/get_bits, commit",
        "// ea99364f61c14656440e8d77e9c233ccf3124633 (CC0-1.0).",
        "// 4 input patterns x 8 bit alignments x widths 1..32 = 1024 reads.",
        "",
        "///|",
        'test "valid reads match pinned minimp3 C helper" {',
        "  let expected : Array[UInt] = [",
    ]
    for start in range(0, len(values), 4):
        lines.append("    " + ", ".join(f"{value}U" for value in values[start:start + 4]) + ",")
    lines.extend([
        "  ]",
        "  for seed in 0..<4 {",
        "    let bytes = Bytes::makei(8, i => (seed * 83 + i * 61).to_byte())",
        "    for offset in 0..<8 {",
        "      for width in 1..=32 {",
        "        let reader = @bitstream.BitReader::new(bytes)",
        "        assert_eq(reader.skip_bits(offset), Ok(()))",
        "        let index = seed * 256 + offset * 32 + width - 1",
        "        assert_eq(reader.read_bits(width), Ok(expected[index]))",
        "        assert_eq(reader.position(), (offset + width).to_int64())",
        "      }",
        "    }",
        "  }",
        "}",
        "",
    ])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Verify the committed fixture without rewriting it")
    parser.add_argument("--cc", default="gcc", help="C compiler executable, defaults to gcc")
    args = parser.parse_args()
    actual_hash = hashlib.sha256(HEADER.read_bytes()).hexdigest()
    if actual_hash != HEADER_SHA256:
        raise SystemExit(f"Pinned minimp3.h SHA256 mismatch: {actual_hash}")
    build_root = ROOT / "target/agents/bitstream-oracle"
    build_root.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="generate-", dir=build_root) as directory:
        executable = Path(directory) / ("oracle.exe" if os.name == "nt" else "oracle")
        subprocess.run([
            args.cc, "-std=c99", "-O2", "-Wall", "-Wextra",
            str(ROOT / "tools/bitstream_oracle.c"), "-o", str(executable), "-lm",
        ], check=True, cwd=ROOT)
        result = subprocess.run([str(executable)], check=True, capture_output=True, text=True)
    source = render([int(line) for line in result.stdout.splitlines()])
    expected = subprocess.run(
        ["moonfmt", "-"], input=source, check=True, capture_output=True, text=True,
    ).stdout
    if args.check:
        if not DESTINATION.exists() or DESTINATION.read_text(encoding="utf-8") != expected:
            raise SystemExit("Bitstream oracle fixture is stale; run tools/generate_bitstream_vectors.py")
        print("Bitstream oracle: 1024 committed vectors match pinned C helper.")
    else:
        DESTINATION.write_text(expected, encoding="utf-8", newline="\n")
        print(f"Wrote {DESTINATION.relative_to(ROOT)} (1024 C oracle vectors).")


if __name__ == "__main__":
    main()
