"""Extract scalar synthesis constants from pinned CC0 minimp3 source."""
from __future__ import annotations

import argparse
import hashlib
from pathlib import Path
import re
import subprocess

ROOT = Path(__file__).resolve().parents[1]
COMMIT = "ea99364f61c14656440e8d77e9c233ccf3124633"
HEADER_SHA256 = "57e437c5c1f0e8b243885d3929c8973b5e6c778451e0100ab4251d19915cb3ad"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--formatter", default="moonfmt")
    args = parser.parse_args()
    source = (ROOT / "third_party/minimp3/minimp3.h").read_bytes()
    if hashlib.sha256(source).hexdigest() != HEADER_SHA256:
        raise SystemExit("minimp3.h differs from the pinned source")
    text = source.decode("ascii")
    lines = [
        "// Generated by tools/generate_synthesis_tables.py; do not edit.",
        f"// minimp3.h commit {COMMIT}, CC0-1.0.",
        f"// Source SHA-256: {HEADER_SHA256}",
        "// Source functions: mp3d_DCT_II and mp3d_synth.",
    ]
    for name, size in [("sec", 24), ("win", 240)]:
        match = re.search(rf"static const float g_{name}\[[^]]*\]\s*=\s*\{{([^}}]+)\}}", text)
        assert match is not None
        values = [v.strip().rstrip("f") for v in match[1].split(",") if v.strip()]
        assert len(values) == size
        values = [v if "." in v else v + ".0" for v in values]
        lines += ["", "///|", f"let synth_{name} : FixedArray[Float] = [", ",\n".join(values) + ",", "]"]
    generated = subprocess.check_output([args.formatter, "-"], input="\n".join(lines).encode(), cwd=ROOT).replace(b"\r\n", b"\n")
    path = ROOT / "internal/layer3/synthesis_tables.mbt"
    if args.check:
        if path.read_bytes() != generated:
            raise SystemExit("Synthesis tables differ; regenerate and review")
        print("Verified 264 scalar synthesis constants against pinned minimp3")
    else:
        path.write_bytes(generated)
        print("Generated 264 scalar synthesis constants")


if __name__ == "__main__":
    main()
