"""Freeze Layer III header expectations from the vendored minimp3 C oracle.

Usage: python tools/generate_header_vectors.py [--check] [--cc gcc]
The --check form reproduces the oracle and requires byte-identical fixtures.
"""
from __future__ import annotations

import argparse
import hashlib
import os
from pathlib import Path
import subprocess


ROOT = Path(__file__).resolve().parents[1]
COMMIT = "ea99364f61c14656440e8d77e9c233ccf3124633"
HEADER_SHA256 = "57e437c5c1f0e8b243885d3929c8973b5e6c778451e0100ab4251d19915cb3ad"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--cc", default="gcc")
    parser.add_argument("--formatter", default="moonfmt")
    args = parser.parse_args()
    source_hash = hashlib.sha256(
        (ROOT / "third_party/minimp3/minimp3.h").read_bytes()).hexdigest()
    if source_hash != HEADER_SHA256:
        raise SystemExit("minimp3.h does not match the pinned upstream source bytes.")
    build = ROOT / "target/agents/header/oracle"
    build.mkdir(parents=True, exist_ok=True)
    exe = build / ("header_oracle.exe" if os.name == "nt" else "header_oracle")
    subprocess.run(
        [args.cc, "-std=c99", "-O2", "-Wall", "-Wextra",
         str(ROOT / "tools/header_oracle.c"), "-o", str(exe), "-lm"],
        cwd=ROOT, check=True,
    )
    output = subprocess.check_output([str(exe)], cwd=ROOT).decode("ascii")
    rows = [[int(value) for value in line.split(",")]
            for line in output.splitlines()]
    assert len(rows) == 2160 and all(len(row) == 12 for row in rows)
    lines = [
        "// Generated by tools/generate_header_vectors.py; do not edit.",
        f"// minimp3 commit: {COMMIT}",
        f"// minimp3.h SHA-256: {source_hash}",
        "// 3 versions x 3 sample rates x 15 bitrate indices x 2 padding",
        "// x 2 CRC states x 4 channel modes = 2160 upstream cases.",
        "// Columns: b1, b2, b3, kbps, Hz, samples, bytes (free size=1000),",
        "// CRC, channels, side-info bytes, mid-side stereo, matches FF FB 90 00.",
        "///|",
        "let oracle_vectors : Array[FixedArray[Int]] = [",
    ]
    lines.extend("  [" + ", ".join(map(str, row)) + "]," for row in rows)
    lines.extend([
        "]", "", "///|",
        'test "all 2160 frozen upstream Layer III header vectors" {',
        '  let compare_base = parse(b"\\xff\\xfb\\x90\\x00").unwrap()',
        "  for row in oracle_vectors {",
        "    let bytes = Bytes::from_array([255, row[0].to_byte(), row[1].to_byte(), row[2].to_byte()])",
        "    let header = parse(bytes).unwrap()",
        "    assert_eq(header.bitrate_kbps, if row[3] == 0 { None } else { Some(row[3]) })",
        "    assert_eq(header.sample_rate_hz, row[4])",
        "    assert_eq(header.samples_per_frame(), row[5])",
        "    assert_eq(header.frame_bytes(free_format_size=1000), Ok(Some(row[6])))",
        "    assert_eq(header.crc_protected, row[7] == 1)",
        "    assert_eq(header.channels(), row[8])",
        "    assert_eq(header.side_info_bytes(), row[9])",
        "    assert_eq(header.mid_side_stereo(), row[10] == 1)",
        "    assert_eq(compare_base.sync_compatible(header), row[11] == 1)",
        "    assert_eq(compare_base.stream_compatible(header), row[11] == 1 && row[8] == 2)",
        "  }", "}", "",
    ])
    generated = subprocess.check_output(
        [args.formatter, "-"], input="\n".join(lines).encode("utf-8"), cwd=ROOT,
    ).replace(b"\r\n", b"\n")
    destination = ROOT / "internal/header/oracle_wbtest.mbt"
    if args.check:
        if destination.read_bytes() != generated:
            raise SystemExit("Header oracle fixture differs; regenerate and review.")
        print(f"Verified {len(rows)} header oracle vectors; minimp3.h {source_hash}")
    else:
        destination.write_bytes(generated)
        print(f"Generated {len(rows)} header oracle vectors; minimp3.h {source_hash}")


if __name__ == "__main__":
    main()
