"""Generate exact continuous synthesis vectors from the pinned scalar C oracle.

The fixture contains only deterministic numeric inputs/outputs and source
identity; compiler paths and other local environment information are not saved.
"""
from __future__ import annotations

import argparse
import hashlib
import os
from pathlib import Path
import struct
import subprocess

ROOT = Path(__file__).resolve().parents[1]
COMMIT = "ea99364f61c14656440e8d77e9c233ccf3124633"
HEADER_SHA256 = "57e437c5c1f0e8b243885d3929c8973b5e6c778451e0100ab4251d19915cb3ad"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--cc", default="gcc")
    parser.add_argument("--formatter", default="moonfmt")
    args = parser.parse_args()
    header = (ROOT / "third_party/minimp3/minimp3.h").read_bytes()
    if hashlib.sha256(header).hexdigest() != HEADER_SHA256:
        raise SystemExit("minimp3.h differs from the pinned source")
    build = ROOT / "target/agents/synthesis/oracle"
    build.mkdir(parents=True, exist_ok=True)
    exe = build / ("synthesis_oracle.exe" if os.name == "nt" else "synthesis_oracle")
    subprocess.run([args.cc, "-std=c99", "-O2", "-Wall", "-Wextra",
                    "-ffp-contract=off", "-fno-fast-math",
                    str(ROOT / "tools/synthesis_oracle.c"), "-o", str(exe), "-lm"],
                   cwd=ROOT, check=True)
    output = subprocess.check_output([str(exe)], cwd=ROOT).decode("ascii")
    rows = [line.split() for line in output.splitlines()]
    assert len(rows) == 22
    lines = [
        "// Generated by tools/generate_synthesis_vectors.py; do not edit.",
        f"// Unmodified minimp3 {COMMIT}, CC0-1.0.",
        f"// minimp3.h SHA-256: {HEADER_SHA256}",
        "// C build: MINIMP3_NO_SIMD, MINIMP3_FLOAT_OUTPUT, -ffp-contract=off.",
        "// Each granule: PCM, 960-cell state, then transformed active grbuf.",
        "// Binary32 words packed little-endian in 256-byte chunks.",
        "///|", "let synth_oracle_vectors : Array[Array[Bytes]] = [",
    ]
    for row in rows:
        mode, nch, step = map(int, row[:3])
        words = [int(value, 16) for value in row[3:]]
        assert len(words) == 1152 * nch + 960
        data = struct.pack(f"<{len(words)}I", *words)
        lines.append(f"  // mode={mode}, channels={nch}, consecutive granule={step}")
        lines.append("  [")
        for offset in range(0, len(data), 256):
            chunk = data[offset:offset+256]
            lines.append('    b"' + "".join(f"\\x{value:02x}" for value in chunk) + '",')
        lines.append("  ],")
    lines += ["]", ""]
    generated = subprocess.check_output([args.formatter, "-"], input="\n".join(lines).encode(), cwd=ROOT).replace(b"\r\n", b"\n")
    path = ROOT / "internal/layer3/synthesis_vectors_wbtest.mbt"
    if args.check:
        if path.read_bytes() != generated:
            raise SystemExit("Synthesis vectors differ; regenerate and review")
        print("Verified 22 continuous-granule synthesis vectors")
    else:
        path.write_bytes(generated)
        print("Generated 22 continuous-granule synthesis vectors")


if __name__ == "__main__":
    main()
