"""Reproduce all-version side-info tables and continuous C reservoir fixtures.

Only deterministic source fixtures are persisted. C executables and any
intermediate artifacts live under ignored target/; no run reports are saved.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import subprocess

ROOT = Path(__file__).resolve().parents[1]
COMMIT = "ea99364f61c14656440e8d77e9c233ccf3124633"
HEADER_SHA256 = "57e437c5c1f0e8b243885d3929c8973b5e6c778451e0100ab4251d19915cb3ad"
CASES = [
    ("tests/corpus/generated/generated-44100-1ch-vbr.mp3", 8),
    ("tests/corpus/generated/generated-48000-2ch-abr.mp3", 8),
    ("tests/corpus/generated/generated-32000-2ch-cbr.mp3", 8),
    ("tests/corpus/upstream/l3-si.bit", 8),
    ("tests/corpus/upstream/l3-si_block.bit", 24),
    ("tests/corpus/upstream/l3-si_huff.bit", 8),
]


def fmt(source: str, formatter: str) -> str:
    return subprocess.check_output(
        [formatter, "-"], input=source.encode(), cwd=ROOT
    ).decode().replace("\r\n", "\n")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--cc", default="gcc")
    parser.add_argument("--formatter", default="moonfmt")
    args = parser.parse_args()
    header = (ROOT / "third_party/minimp3/minimp3.h").read_bytes()
    if hashlib.sha256(header).hexdigest() != HEADER_SHA256:
        raise SystemExit("Vendored minimp3 source does not match pinned hash.")
    table_lines = []
    source_tables = {}
    for kind in ["long", "short", "mixed"]:
        block = re.search(
            rf"g_scf_{kind}\[8\]\[\d+\]\s*=\s*\{{(.*?)\n    \}};",
            header.decode(), re.S,
        ).group(1)
        rows = [[int(v) for v in re.findall(r"\d+", row)]
                for row in re.findall(r"\{([^{}]*)\}", block)]
        assert len(rows) == 8
        source_tables[kind] = rows
        if kind == "mixed":
            # Fixed minimp3's 8 kHz row contains 39 bands but declares 6+30;
            # its first six widths total 48 while mixed IMDCT/reorder starts
            # at 4*18=72. Build the consistent 36-band mixed layout directly
            # from the same pinned CC0 long/short tables, never C overreads.
            corrected = source_tables["long"][1][:6] + source_tables["short"][1][9:]
            assert len(rows[1]) == 40 and sum(rows[1][:6]) == 48
            assert sum(corrected[:6]) == 72 and sum(corrected[6:]) == 504
            assert len(corrected) == 37 and corrected[-1] == 0
            rows[1] = corrected
            table_lines += ["// 8 kHz mixed row is derived from pinned long[:6] + short[9:].",
                            "// This fixes upstream's 48/72 start mismatch and 39/36 band mismatch."]
        table_lines += ["///|", f"let side_scf_{kind} : Array[Array[Int]] = ["]
        for row in rows:
            # C zero-fills the remainder of mixed arrays; we retain the
            # meaningful widths and single terminator consumed by the decoder.
            assert sum(row) == 576 and row[-1] == 0
            table_lines.append("  [" + ", ".join(map(str, row)) + "],")
        table_lines += ["]", ""]
    tables = fmt("\n".join(table_lines), args.formatter)
    source_path = ROOT / "internal/layer3/side_info.mbt"
    source = source_path.read_text(encoding="utf-8")
    start = "// BEGIN GENERATED SCALEFACTOR BAND WIDTHS\n"
    end = "// END GENERATED SCALEFACTOR BAND WIDTHS"
    updated = source.split(start)[0] + start + "\n" + tables + end + source.split(end)[1]
    if args.check:
        if source != updated:
            raise SystemExit("Scalefactor-band tables differ from vendored C source.")
    else:
        source_path.write_text(updated, encoding="utf-8", newline="\n")

    build = ROOT / "target/agents/side_info/oracle"
    build.mkdir(parents=True, exist_ok=True)
    exe = build / ("side_info_oracle.exe" if os.name == "nt" else "side_info_oracle")
    subprocess.run([args.cc, "-std=c99", "-O2", "-Wall", "-Wextra",
                    str(ROOT / "tools/side_info_oracle.c"), "-o", str(exe), "-lm"],
                   check=True, cwd=ROOT)
    lines = [
        "// Generated by tools/generate_side_info_vectors.py; do not edit.",
        f"// minimp3 commit: {COMMIT}; SHA-256: {HEADER_SHA256}",
        "// Actual C Side Info and reservoir outputs for consecutive MPEG-1 frames.",
    ]
    total = 0
    block_types = set()
    reuse_flags = set()
    for case, count in CASES:
        data = (ROOT / case).read_bytes()
        rows = [json.loads(row) for row in subprocess.check_output(
            [str(exe), str(ROOT / case), str(count)], cwd=ROOT).decode().splitlines()]
        assert len(rows) == count
        total += len(rows)
        lines += [f"// Source: {case}; SHA-256: {hashlib.sha256(data).hexdigest()}",
                  "///|", f'test "C continuous side-info and reservoir: {Path(case).stem}" {{',
                  "  let reservoir = Reservoir::new()"]
        for row in rows:
            literal = lambda value: 'b"' + "".join("\\x" + value[i:i+2]
                                                   for i in range(0, len(value), 2)) + '"'
            lines += ["  {", f"    let frame = {literal(row['frame'])}",
                      "    let header = @header.parse(frame).unwrap()",
                      "    let side = read_side_info(frame, header)",
                      f"    assert_eq(side.main_data_begin, {row['begin']})",
                      f"    assert_eq(header.main_data_offset() * 8, {row['side_bits']})",
                      f"    assert_eq(side.granules.length(), {len(row['granules'])})"]
            for index, gr in enumerate(row["granules"]):
                block_types.add((gr[4], gr[5]))
                reuse_flags.add(gr[11])
                lines += [f"    assert_eq(side_flatten(side.granules[{index}]), "
                          + "[" + ", ".join(map(str, gr)) + "])"]
            lines += ["    let offset = header.main_data_offset()",
                      "    let payload = Bytes::makei(frame.length() - offset, fn(i) { frame[offset + i] })",
                      "    let main = reservoir.restore(payload, side.main_data_begin)",
                      f"    assert_eq(main, {literal(row['main'])})",
                      f"    reservoir.save(main, {row['consumed']})",
                      f"    assert_eq(reservoir.history, {literal(row['saved'])})", "  }"]
        lines += ["}", ""]
    assert {(0, 0), (1, 0), (2, 0), (2, 1), (3, 0)} <= block_types
    assert {0, 7, 8, 9, 13, 15} <= reuse_flags
    fixture = fmt("\n".join(lines), args.formatter).encode()
    destination = ROOT / "internal/layer3/side_info_oracle_wbtest.mbt"
    if args.check:
        if destination.read_bytes() != fixture:
            raise SystemExit("Side-info oracle fixtures differ; regenerate and review.")
        print(f"Verified {total} continuous C side-info/reservoir vectors and 24 band tables")
    else:
        destination.write_bytes(fixture)
        print(f"Generated {total} continuous C side-info/reservoir vectors and 24 band tables")


if __name__ == "__main__":
    main()
