"""Reproduce bounded-framing valid-input vectors from pinned minimp3 C helpers."""
from __future__ import annotations

import argparse
import hashlib
import os
from pathlib import Path
import subprocess

ROOT = Path(__file__).resolve().parents[1]
COMMIT = "ea99364f61c14656440e8d77e9c233ccf3124633"
SHA = "57e437c5c1f0e8b243885d3929c8973b5e6c778451e0100ab4251d19915cb3ad"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--cc", default="gcc")
    args = parser.parse_args()
    if hashlib.sha256((ROOT / "third_party/minimp3/minimp3.h").read_bytes()).hexdigest() != SHA:
        raise SystemExit("Vendored minimp3 does not match pinned source.")
    build = ROOT / "target/agents/framing/oracle"
    build.mkdir(parents=True, exist_ok=True)
    exe = build / ("framing.exe" if os.name == "nt" else "framing")
    subprocess.run([args.cc, "-std=c99", "-O2", "-Wall", "-Wextra", "-Werror",
                    "tools/framing_oracle.c", "-o", str(exe), "-lm"], cwd=ROOT, check=True)
    rows = [[int(x) for x in line.split(",")] for line in
            subprocess.check_output([str(exe)], cwd=ROOT, text=True).splitlines()]
    assert len(rows) == 1440 and all(len(row) == 9 for row in rows)
    lines = ["// Generated by tools/generate_framing_vectors.py; do not edit.",
             f"// Unmodified mp3d_find_frame: {COMMIT} (CC0-1.0).", f"// Header SHA-256: {SHA}",
             "///|", "let framing_c_vectors : Array[Array[Int]] = ["]
    lines += ["  [" + ", ".join(map(str, row)) + "]," for row in rows]
    lines += ["]", "///|", 'test "1440 original C free-format discovery vectors" {',
              "  assert_eq(framing_c_vectors.length(), 1440)",
              "  for row in framing_c_vectors {",
              "    let data = framing_stream(row[0], row[1], row[2], row[3], row[4], row[5])",
              "    assert_eq(row[6], 0)",
              "    assert_eq(probe(data, framing_header(data), false, None), Frame(row[7], Some(row[8])))",
              "  }", "}"]
    corpus = ROOT / "tests/corpus/upstream/l3-he_free.bit"
    data = corpus.read_bytes()
    offset, size, base = map(int, subprocess.check_output([str(exe), str(corpus)], cwd=ROOT, text=True).strip().split(","))
    assert offset == 0
    # Keep only the exact two first frames and the third header, sufficient to
    # establish the same spacing without copying the complete audio fixture.
    second = base + ((data[size + 2] >> 1) & 1)
    prefix = data[:size + second + 4]
    lines += [f"// Unmodified tests/corpus/upstream/l3-he_free.bit; SHA-256: {hashlib.sha256(data).hexdigest()}",
              "///|", 'test "real upstream free-format prefix matches C discovery" {',
              '  let data = b"' + "".join(f"\\x{b:02x}" for b in prefix) + '"',
              f"  assert_eq(probe(data, framing_header(data), false, None), Frame({size}, Some({base})))", "}", ""]
    output = subprocess.check_output(["moonfmt", "-"], input="\n".join(lines).encode(), cwd=ROOT).replace(b"\r\n", b"\n")
    dest = ROOT / "internal/framing/oracle_wbtest.mbt"
    if args.check:
        if dest.read_bytes() != output:
            raise SystemExit("Framing C vectors differ; regenerate and review.")
        print("Verified 1440 C free-format vectors and original free-format corpus prefix")
    else:
        dest.write_bytes(output)
        print("Generated 1440 C free-format vectors and original free-format corpus prefix")


if __name__ == "__main__":
    main()
