"""Freeze scalar upstream stereo and hybrid outputs, including continuous overlap.

Only deterministic numeric vectors and upstream source identity are persisted.
"""
from __future__ import annotations

import argparse
import hashlib
import os
from pathlib import Path
import struct
import subprocess

ROOT = Path(__file__).resolve().parents[1]
COMMIT = "ea99364f61c14656440e8d77e9c233ccf3124633"
HEADER_SHA256 = "57e437c5c1f0e8b243885d3929c8973b5e6c778451e0100ab4251d19915cb3ad"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--cc", default="gcc")
    parser.add_argument("--formatter", default="moonfmt")
    args = parser.parse_args()
    header = (ROOT / "third_party/minimp3/minimp3.h").read_bytes()
    if hashlib.sha256(header).hexdigest() != HEADER_SHA256:
        raise SystemExit("minimp3.h differs from the pinned source")
    build = ROOT / "target/agents/transform/oracle"
    build.mkdir(parents=True, exist_ok=True)
    exe = build / ("transform_oracle.exe" if os.name == "nt" else "transform_oracle")
    subprocess.run([args.cc, "-std=c99", "-O2", "-Wall", "-Wextra",
                    "-ffp-contract=off", "-fno-fast-math",
                    str(ROOT / "tools/transform_oracle.c"), "-o", str(exe), "-lm"],
                   cwd=ROOT, check=True)
    output = subprocess.check_output([str(exe)], cwd=ROOT).decode("ascii")
    rows = [line.split() for line in output.splitlines()]
    assert len(rows) == 66
    metadata = [list(map(int, row[:10])) for row in rows]
    assert {row[1] for row in metadata} == {0, 1, 2}
    assert {row[2] for row in metadata} == {0, 1, 2, 3}
    assert {row[5] for row in metadata} == {0, 1, 2, 3}
    assert len({row[0] for row in metadata}) == 42
    lines = [
        "// Generated by tools/generate_transform_vectors.py; do not edit.",
        f"// Unmodified minimp3 {COMMIT}, CC0-1.0.",
        f"// minimp3.h SHA-256: {HEADER_SHA256}",
        "// C build: MINIMP3_NO_SIMD, MINIMP3_FLOAT_OUTPUT, -ffp-contract=off.",
        "// 36 static cases and 30 granules in six five-granule sequences.",
        "// Metadata: group, rate-index, stereo-mode, input, step,",
        "// left block/mixed, right block/mixed, initial PRNG seed.",
        "///|", "let transform_oracle_metadata : Array[FixedArray[Int]] = [",
    ]
    lines += ["  [" + ", ".join(map(str, row)) + "]," for row in metadata]
    lines += ["]", "", "// Binary32 words: stereo[1152], hybrid[1152], overlap[2][288],",
              "// then 39 unsigned intensity positions, packed little-endian.",
              "///|", "let transform_oracle_vectors : Array[Array[Bytes]] = ["]
    for row in rows:
        words = [int(value, 16) for value in row[10:]]
        assert len(words) == 2919
        data = struct.pack(f"<{len(words)}I", *words)
        lines.append(f"  // group={row[0]}, granule={row[4]}")
        lines.append("  [")
        for offset in range(0, len(data), 256):
            lines.append('    b"' + "".join(f"\\x{v:02x}" for v in data[offset:offset+256]) + '",')
        lines.append("  ],")
    lines += ["]", ""]
    generated = subprocess.check_output([args.formatter, "-"], input="\n".join(lines).encode(), cwd=ROOT).replace(b"\r\n", b"\n")
    path = ROOT / "internal/layer3/transform_vectors_wbtest.mbt"
    if args.check:
        if path.read_bytes() != generated:
            raise SystemExit("Transform vectors differ; regenerate and review")
        print("Verified 66 stereo/hybrid/overlap C oracle vectors")
    else:
        path.write_bytes(generated)
        print("Generated 66 stereo/hybrid/overlap C oracle vectors")


if __name__ == "__main__":
    main()
