"""Reproduce all LSF scalefactor partitions, nine-rate side info and DSP fixtures."""
from __future__ import annotations

import argparse
import hashlib
import os
from pathlib import Path
import re
import subprocess

ROOT = Path(__file__).resolve().parents[1]
SHA = "57e437c5c1f0e8b243885d3929c8973b5e6c778451e0100ab4251d19915cb3ad"
COMMIT = "ea99364f61c14656440e8d77e9c233ccf3124633"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--cc", default="gcc")
    args = parser.parse_args()
    header = (ROOT / "third_party/minimp3/minimp3.h").read_bytes()
    assert hashlib.sha256(header).hexdigest() == SHA
    source = header.decode()
    partition_block = re.search(r"g_scf_partitions\[3\]\[28\]\s*=\s*\{(.*?)\n    \};",source,re.S)
    assert partition_block
    partitions = [[int(value) for value in re.findall(r"\d+",row)]
                  for row in re.findall(r"\{([^{}]*)\}",partition_block[1])]
    assert len(partitions) == 3 and all(len(row) == 28 for row in partitions)
    modulus_block = re.search(r"g_mod\[6\*4\]\s*=\s*\{([^}]+)\}",source)
    assert modulus_block
    moduli = [int(value) for value in re.findall(r"\d+",modulus_block[1])]
    assert len(moduli) == 24
    table_lines = ["// Generated from pinned L3_decode_scalefactors; do not edit.",
                   "///|","let scf_partitions : Array[Array[Int]] = ["]
    table_lines += ["  [" + ", ".join(map(str,row)) + "]," for row in partitions]
    table_lines += ["]","///|","let scf_moduli : Array[Int] = [" + ", ".join(map(str,moduli)) + "]",""]
    tables = subprocess.check_output(["moonfmt","-"],input="\n".join(table_lines).encode(),cwd=ROOT).decode().replace("\r\n","\n")
    path = ROOT / "internal/layer3/scalefactors.mbt"
    existing = path.read_text()
    start, end = "// BEGIN GENERATED SCALEFACTOR PARTITIONS\n", "// END GENERATED SCALEFACTOR PARTITIONS"
    updated = existing.split(start)[0] + start + "\n" + tables + end + existing.split(end)[1]
    if args.check:
        if existing != updated:
            raise SystemExit("Scalefactor partition tables differ from pinned C")
    else:
        path.write_text(updated,encoding="utf-8",newline="\n")
    build = ROOT / "target/reference/low-version-oracle"
    build.mkdir(parents=True, exist_ok=True)
    exe = build / ("oracle.exe" if os.name == "nt" else "oracle")
    subprocess.run([args.cc,"-std=c99","-O2","-ffp-contract=off","-fno-fast-math",
                    "-Wall","-Wextra","-Werror",str(ROOT / "tools/low_version_oracle.c"),
                    "-o",str(exe),"-lm"],check=True,cwd=ROOT)
    output = subprocess.check_output([str(exe)],cwd=ROOT).decode("ascii")
    rows = [line.split() for line in output.splitlines()]
    assert len(rows) == 3612
    lines = ["// Generated by tools/generate_low_version_vectors.py; do not edit.",
             f"// Scalar minimp3 primitives {COMMIT} (CC0-1.0).",f"// SHA-256: {SHA}",
             "// 8 kHz mixed cases use fixed-source long[:6]+short[9:] band correction.",
             "// All other cases call unmodified C helpers with their original tables.",
             "// Hashes cover every Float bit/position in order, including signed zero."]
    for kind,name,count in [("S","lsf_scalefactor_vectors",3072),("B","version_side_vectors",180),("T","version_transform_vectors",360)]:
        selected = [row for row in rows if row[0] == kind]
        assert len(selected) == count
        lines += ["", "///|", f"let {name} : Array[Array[UInt]] = ["]
        for row in selected:
            lines.append("  [" + ", ".join(v + "U" for v in row[1:]) + "],")
        lines.append("]")
    data = subprocess.check_output(["moonfmt","-"],input=("\n".join(lines)+"\n").encode(),cwd=ROOT).replace(b"\r\n",b"\n")
    destination = ROOT / "internal/layer3/low_version_vectors_wbtest.mbt"
    if args.check:
        if destination.read_bytes() != data:
            raise SystemExit("Low-version oracle fixtures differ; regenerate and review")
        print("Verified 3612 low-version and nine-rate oracle cases")
    else:
        destination.write_bytes(data)
        print("Generated 3612 low-version and nine-rate oracle cases")


if __name__ == "__main__":
    main()
