"""Reproduce the scalar Huffman/dequantization tables from pinned minimp3."""
from __future__ import annotations

import argparse
import hashlib
from pathlib import Path
import re
import subprocess

ROOT = Path(__file__).resolve().parents[1]
COMMIT = "ea99364f61c14656440e8d77e9c233ccf3124633"
SHA = "57e437c5c1f0e8b243885d3929c8973b5e6c778451e0100ab4251d19915cb3ad"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    raw = (ROOT / "third_party/minimp3/minimp3.h").read_bytes()
    if hashlib.sha256(raw).hexdigest() != SHA:
        raise SystemExit("Pinned minimp3.h checksum mismatch")
    source = raw.decode()
    lines = ["// Generated by tools/generate_spectral_tables.py; do not edit.",
             f"// minimp3.h {COMMIT} (CC0-1.0), L3_huffman and g_pow43.",
             f"// Source SHA-256: {SHA}"]
    specs = [("tabs", "huffman_tabs", "Int", 2164),
             ("tab32", "huffman_count32", "Int", 28),
             ("tab33", "huffman_count33", "Int", 16),
             ("tabindex", "huffman_index", "Int", 32),
             ("g_linbits", "huffman_linbits", "Int", 32),
             ("g_pow43", "pow43_table", "Float", 145)]
    for cname, name, kind, expected in specs:
        match = re.search(r"\b" + cname + r"\[[^]]*\]\s*=\s*\{([^}]+)\}", source)
        assert match, cname
        values = [v.strip().removesuffix("f") for v in match[1].split(",") if v.strip()]
        assert len(values) == expected, (cname, len(values), expected)
        if kind == "Float":
            values = [v if "." in v else v + ".0" for v in values]
        lines.extend(["", "///|", f"let {name} : Array[{kind}] = ["])
        for start in range(0, len(values), 12):
            lines.append("  " + ", ".join(values[start:start + 12]) + ",")
        lines.append("]")
    data = subprocess.check_output(["moonfmt", "-"], input=("\n".join(lines) + "\n").encode(), cwd=ROOT).replace(b"\r\n", b"\n")
    path = ROOT / "internal/layer3/spectral_tables.mbt"
    if args.check:
        if path.read_bytes() != data:
            raise SystemExit("Spectral tables differ; regenerate and review")
        print("Verified all six pinned spectral tables")
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
        print("Generated all six pinned spectral tables")


if __name__ == "__main__":
    main()
