"""Reproduce the scalar stereo/IMDCT tables from the pinned upstream source."""
import argparse
import hashlib
from pathlib import Path
import re
import subprocess

ROOT = Path(__file__).resolve().parents[1]
COMMIT = "ea99364f61c14656440e8d77e9c233ccf3124633"
SHA = "57e437c5c1f0e8b243885d3929c8973b5e6c778451e0100ab4251d19915cb3ad"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    source = (ROOT / "third_party/minimp3/minimp3.h").read_bytes()
    assert hashlib.sha256(source).hexdigest() == SHA
    text = source.decode()
    lines = ["// Generated by tools/generate_transform_tables.py; do not edit.",
             f"// minimp3.h {COMMIT} (CC0-1.0); SHA-256 {SHA}."]
    for name, count in (("g_pan", 14), ("g_aa", 16), ("g_twid9", 18),
                        ("g_twid3", 6), ("g_mdct_window", 36)):
        body = re.search(r"static const float " + name + r"\[.*?=\s*\{(.*?)\};", text, re.S)[1]
        values = re.findall(r"[-+]?\d+(?:\.\d*)?(?:[eE][-+]?\d+)?f?", body)
        assert len(values) == count, (name, len(values))
        values = [v.rstrip("f") if "." in v or "e" in v.lower() else v.rstrip("f") + ".0" for v in values]
        lines += ["", "///|", f"let {name} : Array[Float] = [" + ", ".join(values) + "]"]
    generated = subprocess.check_output(["moonfmt", "-"], input=("\n".join(lines)+"\n").encode(), cwd=ROOT)
    generated = generated.replace(b"\r\n", b"\n")
    path = ROOT / "internal/layer3/transform_tables.mbt"
    if args.check:
        assert path.read_bytes() == generated, "Transform tables changed; regenerate and review"
        print("Stereo/IMDCT tables match pinned minimp3")
    else:
        path.write_bytes(generated)


if __name__ == "__main__":
    main()
