"""Regenerate ID3 boundary tests by running the pinned minimp3 C helpers.

No third-party Python packages. Run from any directory with gcc on PATH.
Generated tests cover the shared valid-input contract, not stricter errors.
"""
from pathlib import Path
import argparse
import os
import subprocess

ROOT = Path(__file__).resolve().parents[1]
COMMIT = "ea99364f61c14656440e8d77e9c233ccf3124633"


def header(version: int, flags: int, payload: int, revision: int) -> bytes:
    size = bytes((payload >> shift) & 127 for shift in (21, 14, 7, 0))
    result = b"ID3" + bytes((version, revision, flags)) + size
    data = result + b"x" * payload
    if version == 4 and flags & 16:
        data += b"3DI" + result[3:]
    return data


def tail(audio: int, enhanced: bool, standard: bool) -> bytes:
    return (b"x" * audio + (b"TAG+" + bytes(223) if enhanced else b"")
            + (b"TAG" + bytes(125) if standard else b""))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cc", default=os.environ.get("CC", "gcc"))
    parser.add_argument("--check", action="store_true", help="Check committed vectors without changing them")
    args = parser.parse_args()
    build = ROOT / "target" / "agents" / "tags" / "oracle"
    build.mkdir(parents=True, exist_ok=True)
    oracle = build / ("tags_oracle.exe" if os.name == "nt" else "tags_oracle")
    subprocess.run([args.cc, "-std=c99", "-O2", str(ROOT / "tools" / "tags_oracle.c"),
                    "-o", str(oracle), "-lm"], check=True)

    def reference(mode: str, data: bytes) -> int:
        return int(subprocess.check_output([str(oracle), mode, data.hex()], text=True).strip())

    lines = [f"// Generated by tools/generate_tags_vectors.py using minimp3 {COMMIT}.",
             "// Do not hand-edit expected boundaries; run the C oracle again.", "", "///|",
             'test "valid leading tags match pinned C oracle" {', "  let cases = ["]
    prefix_count = 0
    for version, flag_values in ((2, (0, 64, 128, 192)),
                                 (3, (0, 32, 64, 128, 224)),
                                 (4, (0, 16, 32, 64, 128, 240))):
        for flags in flag_values:
            for payload in (0, 1, 127, 128, 254, 1024):
                revision = 0 if payload % 2 == 0 else 254
                expected = reference("prefix", header(version, flags, payload, revision))
                lines.append(f"    ({version}, {flags}, {payload}, {revision}, {expected}),")
                prefix_count += 1
    lines += ["  ]", "  for entry in cases {", "    let (version, flags, payload, revision, total) = entry",
              "    let bytes = leading(version, flags, payload, revision~)",
              "    assert_eq(", "      inspect_id3v2(bytes[:], true, total),", "      Tag({",
              "        version,", "        revision,", "        flags,",
              "        payload_bytes: payload,", "        total_bytes: total,",
              "      }),", "    )", "  }", "}", "", "///|",
              'test "valid trailing tags match pinned C oracle" {', "  let cases = ["]
    tail_count = 0
    for audio in (0, 1, 127, 128, 227, 1024):
        for enhanced, standard in ((False, False), (False, True), (True, True), (True, False)):
            expected = reference("tail", tail(audio, enhanced, standard))
            lines.append(f"    ({audio}, {str(enhanced).lower()}, {str(standard).lower()}, {expected}),")
            tail_count += 1
    lines += ["  ]", "  for entry in cases {", "    let (audio, enhanced, standard, expected) = entry",
              "    let bytes = tail(audio, enhanced, standard)", "    let info = trim_id3v1(bytes[:])",
              "    assert_eq(info.tag_bytes, expected)", "    assert_eq(info.audio_end, bytes.length() - expected)",
              "    assert_eq(info.enhanced, enhanced && standard)", "  }", "}", ""]
    output = ROOT / "internal" / "tags" / "upstream_vectors_test.mbt"
    expected = "\n".join(lines)
    if args.check:
        if not output.exists() or output.read_text(encoding="utf-8") != expected:
            raise SystemExit("Committed tag vectors differ; run tools/generate_tags_vectors.py")
    else:
        output.write_text(expected, encoding="utf-8", newline="\n")
    print(f"Tag C oracle: {prefix_count} prefix + {tail_count} tail vectors {'verified' if args.check else 'generated'}")


if __name__ == "__main__":
    main()
